version: 2.1

jobs:
  send-return:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Send a return 1"
          command: "return 1"

      - run:
          name: "Report failure"
          command: "echo job failed!"
          when: on_fail

workflows:
  say-hello-workflow:
    jobs:
      - send-return

